#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int white1;
int black1;
int white2;
int black2;
int r1c, g1c, b1c;
int r2c, g2c, b2c;
bool green1 = false;
bool green2 = false;
int r1, g1, b1;
int r2, g2, b2;
float hh;



task main()
{
	repeat(10)
	{
		getColorRawRGB(S1, r1c, g1c, b1c);
		getColorRawRGB(S2, r2c, g2c, b2c);
		sleep(50);
	}
	nMotorEncoder[motorB] = 0;
	getColorRawRGB(S1, r1c, g1c, b1c);
	getColorRawRGB(S2, r2c, g2c, b2c);
	white1 = g1c;
	black1 = g1c;
	white2 = g2c;
	black2 = g2c;
	setMotorBrakeMode(motorB, motorCoast);
	setMotorBrakeMode(motorC, motorCoast);



	while(!getButtonPress(buttonEnter))
	{
		getColorRawRGB(S1, r1c, g1c, b1c);
		getColorRawRGB(S2, r2c, g2c, b2c);
		if(g1c > white1)
			white1 = g1c;
		if(g1c < black1)
			black1 = g1c;
		if(g2c > white2)
			white2 = g2c;
		if(g2c < black2)
			black2 = g2c;
		sleep(10);
	}

	hh = fileOpenWrite("parameters.dat");
	fileWriteFloat(hh, white1);
	fileWriteFloat(hh, black1);
	fileWriteFloat(hh, white2);
	fileWriteFloat(hh, black2);
	fileClose(hh);

	displayBigTextLine(2,"black2: %d",black2);
	displayBigTextLine(5,"white1: %d",white1);
	displayBigTextLine(7,"black1: %d",black1);
	displayBigTextLine(9,"white2: %d",white2);
	sleep(50000);
}
